[FEATURE][TOOLS-CDC]:add flink Command line support
oceanbase/flink-connector-oceanbase pull request #105
Opened 2024-11-12 02:30 UTC by xxsc0529

## Summary

When synchronizing data to OceanBase, the flink CLI is supported. close #101

## Solution Description

Define program entries, receive parameters, and parse them. Use Oceanbase Catalog to obtain the information required by Flink and create the corresponding sink。Here's how it works.
`CREATE TABLE test_history (
    itemid BIGINT NOT NULL,
    clock INT DEFAULT 0 NOT NULL,
    value DOUBLE PRECISION DEFAULT 0.0000 NOT NULL,
    ns INT DEFAULT 0 NOT NULL,
    PRIMARY KEY (itemid, clock, ns)
) ;

CREATE TABLE test_history_uint (
    itemid BIGINT NOT NULL,
    clock INT DEFAULT 0 NOT NULL,
    value DECIMAL(20,0) DEFAULT 0 NOT NULL,
    ns INT DEFAULT 0 NOT NULL,
    PRIMARY KEY (itemid, clock, ns)
) ;

CREATE TABLE test_history_str (
    itemid BIGINT NOT NULL,
    clock INT DEFAULT 0 NOT NULL,
    value VARCHAR(255) DEFAULT '' NOT NULL,
    ns INT DEFAULT 0 NOT NULL,
    PRIMARY KEY (itemid, clock, ns)
);`
The command line is as follows
`./bin/flink run \
    -Dexecution.checkpointing.interval=10s \
    -Dparallelism.default=1 \
    -c com.oceanbase.connector.flink.tools.cdc.CdcTools \
    lib/flink-connector-oceanbase-tools-cdc-1.4-SNAPSHOT.jar \
    mysql-sync-database \
    --database test_db \
    --mysql-conf hostname=xxxx \
    --mysql-conf port=3306 \
    --mysql-conf username=root \
    --mysql-conf password=xxxx \
    --mysql-conf database-name=test_db \
    --including-tables "tbl1|test.*" \
    --sink-conf username=xxxx@xxxx \
    --sink-conf password=xxxx \
    --sink-conf url=jdbc:mysql://xxxx:xxxx  \
    --sink-conf  sink.label-prefix=label  \
    --table-conf  replication_num=1`
The sink-config configuration is the configuration of the OceanBase database

2024-11-28 09:51 UTC, whhe commented on flink-connector-oceanbase-tools-cdc/src/main/java/com/oceanbase/connector/flink/tools/catalog/OceanBaseSchemaFactory.java
> +        System.out.println("Generated DDL: " + sb);
Please use logger but not System.out, check it in other files as well.

2024-11-28 09:51 UTC, whhe commented on flink-connector-oceanbase-tools-cdc/src/main/java/com/oceanbase/connector/flink/table/OceanBaseJsonSerializationSchema.java
> +            log.error("Failed to parse rowData JSON: {}", rowDataStr, e);
Why not throw the exception out?

2024-11-28 09:51 UTC, whhe commented on flink-connector-oceanbase-tools-cdc/src/main/java/com/oceanbase/connector/flink/tools/catalog/FieldSchema.java
> +    private String name;
In what scenarios will these fields be modified? How about make these fields final and remove all setters?

2024-11-28 09:51 UTC, whhe commented on flink-connector-oceanbase-tools-cdc/src/main/java/com/oceanbase/connector/flink/tools/catalog/OceanBaseSchemaFactory.java
> +    public static String identifier(String name) {
Better to use OceanBaseDialect.quoteIdentifier

2024-11-28 09:51 UTC, whhe commented on flink-connector-oceanbase-tools-cdc/src/main/java/com/oceanbase/connector/flink/tools/catalog/TableSchema.java
> +    public static final String DORIS_TABLE_REGEX = "^[a-zA-Z][a-zA-Z0-9-_]*$";
Unrelated field.

2024-11-28 09:51 UTC, whhe commented on flink-connector-oceanbase-tools-cdc/src/main/java/com/oceanbase/connector/flink/tools/catalog/TableSchema.java
> +    private Integer tableBuckets;
What is tableBuckets used for?

2024-11-28 09:51 UTC, whhe commented on flink-connector-oceanbase-tools-cdc/src/main/java/com/oceanbase/connector/flink/tools/cdc/SourceSchema.java
> +    public abstract String getCdcTableName();
Seems it is not necessary while there is already a method getTableIdentifier here.

2024-11-28 09:51 UTC, whhe commented on flink-connector-oceanbase-tools-cdc/src/main/java/com/oceanbase/connector/flink/tools/cdc/CdcTools.java
> +        boolean singleSink = params.has(DatabaseSyncConfig.SINGLE_SINK);
What is it used for?

2024-11-28 09:51 UTC, whhe commented on flink-connector-oceanbase-tools-cdc/src/main/java/com/oceanbase/connector/flink/tools/cdc/DatabaseSyncConfig.java
> +    public static final String MYSQL_SYNC_DATABASE = "mysql-sync-database";
There should be a short description for every config key.

2024-11-28 09:54 UTC, whhe commented
There should be at least a test case for mysql cdc, please add one on the github workflow.

2024-11-29 03:19 UTC, yuanoOo requested changes
Thanks for your contribution, I left some comments.

2024-11-29 03:19 UTC, yuanoOo commented on flink-connector-oceanbase-tools-cdc/src/main/java/com/oceanbase/connector/flink/table/OceanBaseJsonSerializationSchema.java
> +    private static final Logger log =
It is best to use uppercase letters to be consistent with other places.

2024-11-29 03:19 UTC, yuanoOo commented on flink-connector-oceanbase-tools-cdc/src/main/java/com/oceanbase/connector/flink/tools/catalog/OceanBaseSchemaFactory.java
> +    private static List<String> buildDistributeKeys(
What does DistributeKeys mean in oceanbase, oceanbase only has index keys and partition keys.

2024-11-29 03:19 UTC, yuanoOo commented on flink-connector-oceanbase-tools-cdc/src/main/java/com/oceanbase/connector/flink/tools/catalog/OceanBaseSchemaFactory.java
> +        sb = sb.deleteCharAt(sb.length() - 1); // 删除最后一个逗号
Do not use Chinese.

2024-11-29 03:19 UTC, yuanoOo commented on flink-connector-oceanbase-tools-cdc/src/main/java/com/oceanbase/connector/flink/tools/catalog/OceanBaseSystem.java
> +public class OceanBaseSystem implements Serializable {
Better to change the name, it's confusing.

2024-12-02 06:30 UTC, yuanoOo commented on flink-connector-oceanbase-tools-cdc/src/main/java/com/oceanbase/connector/flink/tools/catalog/OceanBaseType.java
> +    public static final String DECIMAL_V3 = "DECIMALV3";
What does this mean? ob does not support this type.

2024-12-02 06:30 UTC, yuanoOo commented on flink-connector-oceanbase-tools-cdc/src/main/java/com/oceanbase/connector/flink/tools/catalog/OceanBaseType.java
> +    public static final String BIGINT_UNSIGNED = "BIGINT UNSIGNED";
Does ob support this type?

2024-12-02 06:30 UTC, yuanoOo commented on flink-connector-oceanbase-tools-cdc/src/main/java/com/oceanbase/connector/flink/tools/catalog/OceanBaseType.java
> +    public static final String DATE_V2 = "DATEV2";
And this

2024-12-02 06:30 UTC, yuanoOo commented on flink-connector-oceanbase-tools-cdc/src/main/java/com/oceanbase/connector/flink/tools/catalog/OceanBaseType.java
> +    public static final String DATETIME_V2 = "DATETIMEV2";
And this

2024-12-02 06:30 UTC, yuanoOo commented on flink-connector-oceanbase-tools-cdc/src/main/java/com/oceanbase/connector/flink/tools/catalog/OceanBaseType.java
> +    public static final String BITMAP = "BITMAP";
And these three

2024-12-02 06:30 UTC, yuanoOo commented on flink-connector-oceanbase-tools-cdc/src/main/java/com/oceanbase/connector/flink/tools/catalog/OceanBaseTypeMapper.java
> +    public static final int MAX_VARCHAR_SIZE = 65533;
I remember it was 262144

2024-12-02 06:30 UTC, yuanoOo commented on flink-connector-oceanbase-tools-cdc/src/main/java/com/oceanbase/connector/flink/tools/catalog/OceanBaseTypeMapper.java
> +    public static final int MAX_CHAR_SIZE = 255;
I remember it was 256

2024-12-04 01:58 UTC, closed without merging